# Generated by Django 3.2.11 on 2022-02-20 19:27

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default-profile.png', upload_to='profile_pictures')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('service_field', models.CharField(choices=[('Actuators', 'Actuators'), ('Pipes and Valves', 'Pipes and Valves'), ('Pricing/Quotation', 'Pricing/Quotation'), ('Service and Repair', 'Service and Repair')], default='Service and Repair', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Engineer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EngineerServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_total', models.IntegerField(default=0)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EngineerServiceField', to='appointments.engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profile_pictures')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('company_name', models.CharField(default='company_name', max_length=300)),
                ('company_address', models.CharField(default='company_address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedCustomerAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField()),
                ('description', models.TextField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerApprovedApp', to='appointments.customer')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorApprovedApp', to='appointments.engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('app_link', models.TextField(blank=True, null=True)),
                ('app_date', models.DateField(blank=True, null=True)),
                ('app_time', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerApp', to='appointments.customer')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EngineerApp', to='appointments.engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default-profile.png', upload_to='profile_pictures')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
